### ISSUE TITLE
Move to ember-fastboot organization?

### ISSUE THREAD

**Issue by bobisjan** [tomdale/fastboot-s3-notifier#11]
Hi 👋,

does it make sense to move this repository under @ember-fastboot organization?

**Comment by bobisjan** [comment]
What do you think guys @tomdale @rwjblue?

**Comment by rwjblue** [comment]
seems good to me, but @tomdale would need to do the honors (personal repos can only be moved by the owner)

**Comment by tomdale** [comment]
Will do

**Comment by tomdale** [comment]
Done
