### ISSUE TITLE
LastModified comparison not working with AWS-SDK 2.29+

### ISSUE THREAD

**Issue by bobisjan** [tomdale/fastboot-s3-notifier#4]
Hi,

in AWS SDK v2.29.0 the type of `LastModified` has changed from `string` to `object`, so comparison at [line](https://github.com/tomdale/fastboot-s3-notifier/blob/master/index.js#L57) doesn't work as expected.

Jan

**Comment by nanaewusi** [comment]
It is same for me. Results in false positives:

<img width="1152" alt="screen shot 2017-03-21 at 10 59 45 pm" src="https://cloud.githubusercontent.com/assets/3534919/24174729/1252a18c-0e8a-11e7-9dc0-66524829f86b.png">

**Comment by chuck** [comment]
Could we please get a new release of fastboot-s3-notifier that includes this fix?

**Comment by tomdale** [comment]
Published 0.1.2

**Comment by chuck** [comment]
Thank you!
